services:
  db:
    image: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME_PROD
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "$DB_PORT:$DB_PORT"
  web:
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - "$NODE_DOCKER_PORT:$NODE_DOCKER_PORT"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME_PROD
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true