services:
  db:
    image: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "$POSTGRES_PORT_LOCAL:$POSTGRES_PORT"
  web:
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - "$NODE_PORT_LOCAL:$NODE_PORT"
    environment:
      - NODE_ENV=$NODE_ENV
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=$POSTGRES_PORT
    stdin_open: true
    tty: true